[package]
name = "pg_wire"
version = "0.5.0"
description = "Server Side implementation of PostgreSQL Wire Protocol"
license = "Apache-2.0"
repository = "https://github.com/alex-dukhno/pg_wire"
keywords = ["protocol", "postgresql", "postgres", "database"]
authors = ["Alex Dukhno <alex.dukhno@icloud.com>", "Steven <asongala@163.com>"]
edition = "2018"
include = [
    "src/**/*.rs",
    "Cargo.toml",
]

[dependencies]
log = "0.4.11"
