name: ci

on:
  push:
    branches: [ main ]

defaults:
  run:
    shell: bash

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-tarpaulin
          version: 0.14.0
          use-tool-cache: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all --features mock_net
      - uses: actions-rs/cargo@v1
        with:
          command: tarpaulin
          args: --all --ignore-tests -o Lcov --output-dir ./coverage --features mock_net
      - uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
