name: Publish Release Bundle

on:
  release:
    types: [published]

defaults:
  run:
    shell: bash

env:
  RUST_BACKTRACE: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/cargo@v1
        with:
          command: publish
          args:  --features mock_net --token ${{ secrets.CRATES_TOKEN }}
